(function(g){var window=this;var xva=function(a,b){var c=[];g.Wk(b,function(a){var b;try{b=g.Nm.prototype.o.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.Zh(b)&&c.push(a):c.push(a)},a);
return c},yva=function(a,b){var c=xva(a,b);
(0,g.L)(c,function(a){g.Nm.prototype.remove.call(this,a)},a)},j9=function(a,b){g.g_.call(this,g.M("YTP_MDX_TITLE"),0,a,b);
this.W=a;this.F={};this.V(a,"onMdxReceiversChange",this.H);this.V(a,"presentingplayerstatechange",this.H);this.H()},zva=function(){var a=g.Gv;
yva(a,a.g.Md(!0))},Ava=function(a){return a.H?a.F+((0,g.D)()-a.A)/1E3:a.F},k9=function(a){g.Qi("cloudview",a)},l9=function(a){g.Ju.call(this,"ScreenServiceProxy");
this.Tc=a;this.o=[];this.o.push(this.Tc.$_s("screenChange",(0,g.B)(this.sQ,this)));this.o.push(this.Tc.$_s("onlineScreenChange",(0,g.B)(this.PM,this)))},Bva=function(a){k9("setApiReady_ "+a);
g.v("yt.mdx.remote.cloudview.apiReady_",a,void 0)},m9=function(){return g.x("yt.mdx.remote.cloudview.instance_")},Cva=function(a){g.js[a]&&(a=g.js[a],(0,g.L)(a,function(a){g.hs[a]&&delete g.hs[a]}),a.length=0)},n9=function(){return g.x("yt.mdx.remote.connection_")},o9=function(a){g.v("yt.mdx.remote.connectData_",a,void 0)},Dva=function(a){g.v("yt.mdx.remote.currentScreenId_",a,void 0)},p9=function(){return g.x("yt.mdx.remote.currentScreenId_")},r9=function(){if(!q9){var a=g.x("yt.mdx.remote.screenService_");
q9=a?new l9(a):null}return q9},s9=function(a){g.v("yt.mdx.remote.cloudview.initializing_",a,void 0)},t9=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},u9=function(a){k9("setCastInstalled_ "+a);
g.Iv("yt-remote-cast-installed",a)},v9=function(a){g.Qi("cloudview",a)},Eva=function(a,b){m9().init(a,b)},w9=function(){return!!g.Jv("yt-remote-cast-installed")},Fva=function(){k9("dispose");
var a=m9();a&&a.dispose();g.v("yt.mdx.remote.cloudview.instance_",null,void 0);Bva(!1);g.ls(x9);x9.length=0},Gva=function(){var a=window.document.createElement("a");
g.Kn(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.jc(a)},Hva=function(a,b){var c=window.document.createElement("script");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
c.src="https://www.gstatic.com/cv/js/sender/v1/cast_sender.js";var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Iva=function(a){var b=g.gs();
if(b)if(b.clear(a),a)Cva(a);else for(var c in g.js)Cva(c)},y9=function(){return g.x("yt.mdx.remote.channelParams_")||{}},A9=function(a){var b=n9();
o9(null);a||Dva("");g.v("yt.mdx.remote.connection_",a,void 0);z9&&((0,g.L)(z9,function(b){b(a)}),z9.length=0);
b&&!a?g.os("yt-remote-connection-change",!1):!b&&a&&g.os("yt-remote-connection-change",!0)},Jva=function(){return g.x("yt.mdx.remote.connectData_")},B9=function(){var a=p9();
if(!a)return null;var b=r9().Rd();return g.ql(b,a)},Kva=function(a,b){u9(!0);
s9(!1);Eva(a,function(a){a?(Bva(!0),g.ms("yt-remote-cast2-api-ready")):(v9("Failed to initialize cast API."),u9(!1),g.Kv("yt-remote-cast-available"),g.Kv("yt-remote-cast-receiver"),Fva());b(a)})},Lva=function(){return w9()?m9()?m9().getCastSession():(v9("getCastSelector: Cast is not initialized."),null):(v9("getCastSelector: Cast API is not installed!"),null)},Mva=function(){var a=Gva(),b=window.document.getElementById(a),c=b&&g.Cc(b,"loaded");
c||b&&!c||(b=Hva(a,function(){g.Cc(b,"loaded")||(g.Dc(b,"loaded","true"),g.ms(a),g.ak(g.ya(Iva,a),0))}))},Nva=function(a){return(0,g.O)(a,function(a){return{key:a.id,
name:a.name}})},Ova=function(){if(g.poa){var a=2,b=g.Ea(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;g.Ja("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",g.Ga,c)}},D9=function(a,b){p9();
B9()&&B9();Dva(a.id);var c=new g.CO(C9,a,y9());c.connect(b,Jva());c.subscribe("beforeDisconnect",function(a){g.os("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){n9()&&(n9(),A9(null))});
A9(c)},E9=function(){var a=g.Bx();
if(!a)return null;var b=r9().Rd();return g.ql(b,a)},F9=function(a){g.Qi("remote",a)},G9=function(){var a=n9();
return!!a&&3!=a.getProxyState()},H9=function(){t9()?m9().stopSession():v9("stopSession called before API ready.");
var a=n9();a&&(a.disconnect(1),A9(null))},Pva=function(){var a;
a=r9().Tc.$_gos();var b=B9();b&&n9()&&(g.pl(a,b)||a.push(b));return Nva(a)},J9=function(a,b){g.fs.call(this);
this.g=0;this.B=a;this.D=[];this.C=new g.bi;this.A=this.o=null;this.H=(0,g.B)(this.ZK,this);this.F=(0,g.B)(this.Bk,this);this.G=(0,g.B)(this.YK,this);this.J=(0,g.B)(this.mL,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Ps,this),Qva(this))):c=3;0!=c&&(b?this.Ps(c):g.ak((0,g.B)(function(){this.Ps(c)},this),0));
var d=Lva();d&&I9(this,d);this.subscribe("yt-remote-cast2-session-change",this.J)},K9=function(a){return new g.ce(a.B.getPlayerContextData())},Rva=function(a,b,c,d,e){var f=K9(a),k=e||f.listId;
d=d||0;var l={videoId:b,currentIndex:d};g.ge(f,b,d);g.t(c)&&(g.ee(f,c),l.currentTime=c);g.t(k)&&(l.listId=k);L9(a,"setPlaylist",l);e||M9(a,f)},Qva=function(a){(0,g.L)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.D.push(this.B.subscribe(a,g.ya(this.jN,a),this))},a)},Sva=function(a){(0,g.L)(a.D,function(a){this.B.unsubscribeByKey(a)},a);
a.D.length=0},N9=function(a,b){50>a.C.Cc()&&g.di(a.C,b)},O9=function(a,b,c){var d=K9(a);
g.ee(d,c);-1E3!=d.g&&(d.g=b);M9(a,d)},L9=function(a,b,c){a.B.sendMessage(b,c)},M9=function(a,b){Sva(a);
a.B.setPlayerContextData(g.he(b));Qva(a)},I9=function(a,b){a.A&&(a.A.removeUpdateListener(a.H),a.A.removeMediaListener(a.F),a.Bk(null));
a.A=b;a.A&&(P9("Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.H),a.A.addMediaListener(a.F),a.A.media.length&&a.Bk(a.A.media[0]))},Tva=function(a){var b=a.o.media,c=a.o.customData;
if(b&&c){var d=K9(a);b.contentId!=d.videoId&&P9("Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;g.ee(d,a.o.getEstimatedTime());M9(a,d)}else P9("No cast media video. Ignoring state update.")},P9=function(a){g.Qi("CP",a)},Q9=function(a,b,c){return(0,g.B)(function(a){this.dc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.dc("Retrying "+b+" using MDx browser channel."),L9(this,b,c))},a)},Uva=function(a){var b=!1;
m9()||(a=new g.OL(a),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Iv("yt-remote-cast-available",a);g.os("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){k9("onReceiverSelected: "+a.friendlyName);
g.Iv("yt-remote-cast-receiver",a);g.os("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){k9("onReceiverResumed: "+a.friendlyName);
g.Iv("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){k9("onSessionChange: "+g.Yi(a));
a||g.Kv("yt-remote-cast-receiver");g.os("yt-remote-cast2-session-change",a)}),g.v("yt.mdx.remote.cloudview.instance_",a,void 0),b=!0);
k9("cloudview.createSingleton_: "+b);return b},Vva=function(){var a=0<=g.Kd.search(/\ (CrMo|Chrome|CriOS)\//);
return g.jp||a},R9=function(a,b){t9()?m9().setConnectedScreenStatus(a,b):v9("setConnectedScreenStatus called before ready.")},Wva=function(){k9("clearCurrentReceiver");
g.Kv("yt-remote-cast-receiver")},Xva=function(){if(0<=window.navigator.userAgent.indexOf("CriOS")){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
if(a){Ova();a({command:"cast.sender.init"});return}}if(window.chrome)if(Ova(),a=window.navigator.userAgent,0<=a.indexOf("Android")&&0<=a.indexOf("Chrome/")&&window.navigator.presentation){var a="",b=g.Ca();55<=b?a="55":50<=b&&(a="50");g.Ja("//www.gstatic.com/eureka/clank"+a+g.Ha,g.Ga)}else g.Ka(0);else g.Ga()},Yva=function(a){a?(g.Iv("yt-remote-session-app",a.app),g.Iv("yt-remote-session-name",a.name)):(g.Kv("yt-remote-session-app"),g.Kv("yt-remote-session-name"));
g.v("yt.mdx.remote.channelParams_",a,void 0)},Zva=function(){var a=y9();
if(g.Ib(a)){var a=g.Ax(),b=g.Jv("yt-remote-session-name")||"",c=g.Jv("yt-remote-session-app")||"",a={device:"REMOTE_CONTROL",id:a,name:b,app:c,"mdx-version":3};g.v("yt.mdx.remote.channelParams_",a,void 0)}},$va=function(){var a=E9();
a?(F9("Resume connection to: "+g.Yi(a)),D9(a,0)):(g.Jx(),Wva(),F9("Skipping connecting because no session screen found."))},awa=function(a){F9("remote.onCastSessionChange_: "+g.Yi(a));
if(a){var b=B9();b&&b.id==a.id?R9(b.id,"YouTube TV"):(b&&H9(),D9(a,1))}else n9()&&H9()},bwa=function(){var a=Pva(),b=B9();
b||(b=E9());return g.xe(a,function(a){return b&&g.Vi(b,a.key)?!0:!1})},cwa=function(){var a=g.Jv("yt-remote-cast-receiver");
return a?a.friendlyName:null},dwa=function(a,b,c,d){Vva()?Uva(b)&&(s9(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Kva(a,c):(window.__onGCastApiAvailable=function(b,d){b?Kva(a,c):(v9("Failed to load cast API: "+d),u9(!1),s9(!1),g.Kv("yt-remote-cast-available"),g.Kv("yt-remote-cast-receiver"),Fva(),c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Mva():Xva())):k9("Cannot initialize because not running Chrome")},
ewa=function(a){this.port=this.A="";
this.g="/api/lounge";this.o=!0;a=a||window.document.location.href;var b=g.Af(a)||"";b&&(this.port=":"+b);this.A=g.zf(a)||"";a=g.Kd;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.ic(a,"10.0")&&(this.o=!1))},S9=function(){var a=bwa();
!a&&w9()&&cwa()&&(a={key:"cast-selector-receiver",name:cwa()});return a},fwa=function(){var a=Pva();
w9()&&g.Jv("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},gwa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};g.Gv&&zva();g.Dx();C9||(C9=new ewa,g.Lx()&&(C9.g="/api/loungedev"));z9||(z9=g.x("yt.mdx.remote.deferredProxies_")||[],g.v("yt.mdx.remote.deferredProxies_",z9,void 0));Zva();var c=r9();if(!c){var d=new g.tF(C9);g.v("yt.mdx.remote.screenService_",d,void 0);c=r9();dwa(a,d,function(a){a?p9()&&R9(p9(),"YouTube TV"):d.subscribe("onlineScreenChange",function(){g.os("yt-remote-receiver-availability-change")})},!(!b||!b.loadCastApiSetupScript))}b&&!g.x("yt.mdx.remote.initialized_")&&
(g.v("yt.mdx.remote.initialized_",!0,void 0),F9("Initializing: "+g.pb(b)),T9.push(g.ks("yt-remote-cast2-availability-change",function(){g.os("yt-remote-receiver-availability-change")})),T9.push(g.ks("yt-remote-cast2-receiver-selected",function(){o9(null);
g.os("yt-remote-auto-connect","cast-selector-receiver")})),T9.push(g.ks("yt-remote-cast2-receiver-resumed",function(){g.os("yt-remote-receiver-resumed","cast-selector-receiver")})),T9.push(g.ks("yt-remote-cast2-session-change",awa)),T9.push(g.ks("yt-remote-connection-change",function(a){a?R9(p9(),"YouTube TV"):E9()||(R9(null,null),Wva())})),a=y9(),b.isAuto&&(a.id+="#dial"),g.Wf("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,F9(" -- with channel params: "+g.pb(a)),
Yva(a),c.start(),p9()||$va())},U9=function(){w9()?m9()?t9()?(k9("Requesting cast selector."),m9().requestSession()):(k9("Wait for cast API to be ready to request the session."),x9.push(g.ks("yt-remote-cast2-api-ready",U9))):v9("requestCastSelector: Cast is not initialized."):v9("requestCastSelector: Cast API is not installed!")},V9=function(a,b,c){g.J.call(this);
this.H=a;this.W=b;b.addEventListener("onVolumeChange",this.sn,this);b.addEventListener("onCaptionsTrackListChanged",this.Yy,this);b.addEventListener("captionschanged",this.My,this);b.addEventListener("captionssettingschanged",this.gs,this);b.addEventListener("videoplayerreset",this.Ek,this);b.addEventListener("mdxautoplaycancel",this.Lu,this);this.C=!1;this.g=c;c.subscribe("proxyStateChange",this.mz,this);c.subscribe("remotePlayerChange",this.Dk,this);c.subscribe("remoteQueueChange",this.Ek,this);
c.subscribe("autoplayUpNext",this.Ky,this);c.subscribe("previousNextChange",this.jz,this);c.subscribe("nowAutoplaying",this.bz,this);c.subscribe("autoplayDismissed",this.Jy,this);this.suggestion=null;this.D=new g.XH(64);this.o=new g.rz(this.yA,500,this);g.K(this,this.o);this.A=new g.rz(this.zA,1E3,this);g.K(this,this.A);this.B={};this.G=new g.rz(this.OA,1E3,this);g.K(this,this.G);this.F=new g.uz(this.jS,1E3,this);g.K(this,this.F);this.J=g.y;this.gs();this.Ek();this.Dk()},W9=function(a,b){var c=a.H,
d=a.W.getVideoData().lengthSeconds;
c.H=b||0;c.g.U("progresssync",b,d)},hwa=function(a){W9(a,0);
a.o.stop();X9(a,new g.XH(64))},$9=function(a,b){if(Y9(a)&&!a.C){var c=null;
b&&(c={style:a.W.dl()},g.Ob(c,b));a.g.sA(Z9(a),c);a.B=K9(a.g).o}},a$=function(a,b){var c=a.W.Wf();
c?Rva(a.g,Z9(a),b,c.Pd(),c.listId.toString()):Rva(a.g,Z9(a),b);X9(a,new g.XH(1))},iwa=function(a,b){if(b){var c=a.W.Wc("captions","tracklist",{Zw:1});
c&&c.length?(a.W.Fe("captions","track",b),a.C=!1):(a.W.Yk("captions"),a.C=!0)}else a.W.Fe("captions","track",{})},Y9=function(a){return K9(a.g).videoId==Z9(a)},Z9=function(a){return a.W.getVideoData().videoId},X9=function(a,b){a.A.stop();
var c=a.D;if(!g.cI(c,b)){var d=g.H(b,2);if(d!=g.H(a.D,2)){var e=a.W;(e=g.aY(e.app,e.playerType||1))&&g.XW(e,d)}a.D=b;jwa(a.H,c,b)}},b$=function(a){g.W.call(this,{K:"div",
Y:"ytp-remote",R:[{K:"div",Y:"ytp-remote-display-status",R:[{K:"div",Y:"ytp-remote-display-status-icon",R:[g.qi()]},{K:"div",Y:"ytp-remote-display-status-text",R:["{{statustext}}"]},{K:"div",Y:"ytp-remote-display-status-receiver",R:["{{receiver}}"]}]}]});this.g=new g.RC(this,250);g.K(this,this.g);this.A=a;this.V(a,"presentingplayerstatechange",this.B);kwa(this,g.WF(a))},kwa=function(a,b){if(3==a.A.Ya()){var c;
c=g.H(b,128)?g.M("YTP_MDX_STATUS_ERROR"):b.sb()||g.H(b,4)?g.M("YTP_MDX_STATUS_PLAYING"):g.M("YTP_MDX_STATUS_CONNECTED");var d=a.A.Wc("remote","currentReceiver");a.update({statustext:c,receiver:d.name});a.g.show()}else g.TC(a.g)},c$=function(a){g.Tu.call(this,a);
this.A={key:g.ol(),name:g.M("YTP_MDX_MY_COMPUTER")};this.C=null;this.D=[];this.J=this.o=null;this.G=[this.A];this.B=this.A;this.F=new g.XH(64);this.H=0;var b=g.VX(a).C;b&&(b=b.A&&b.A.g)&&(b=new j9(a,b),g.K(this,b));b=new b$(a);g.K(this,b);g.qY(a,b.element,5)},jwa=function(a,b,c){a.F=c;
a.g.U("presentingplayerstatechange",new g.bd(c,b))},d$=function(a,b){if(b.key!=a.B.key)if(b.key==a.A.key)H9();
else{a.B=b;var c;c=a.g.getPlaylistId();var d=a.g.getVideoData().videoId;if(c||d){var e,f=a.g.Wf();if(f){e=[];for(var k=0;k<f.getLength();k++)e[k]=f.Yb(k).videoId}else e=[a.g.getVideoData().videoId];c={videoIds:e,listId:c,videoId:d,index:Math.max(a.g.lB(),0),currentTime:a.g.getCurrentTime()}}else c=null;F9("Connecting to: "+g.pb(b));"cast-selector-receiver"==b.key?(o9(c||null),c=c||null,t9()?m9().setLaunchParams(c):v9("setLaunchParams called before ready.")):!c&&G9()&&p9()==b.key?g.os("yt-remote-connection-change",
!0):(H9(),o9(c||null),c=r9().Rd(),(c=g.ql(c,b.key))&&D9(c,1))}};
g.p(j9,g.g_);j9.prototype.H=function(){var a=this.W.Wc("remote","receivers");a&&1<a.length&&!this.W.Wc("remote","quickCast")?(this.F=g.We(a,this.B,this),g.i_(this,(0,g.O)(a,this.B)),a=this.W.Wc("remote","currentReceiver"),g.h_(this,this.B(a)),this.enable(!0)):this.enable(!1)};
j9.prototype.B=function(a){return a.key};
j9.prototype.Le=function(a){return"cast-selector-receiver"==a?g.M("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
j9.prototype.fd=function(a){g.g_.prototype.fd.call(this,a);this.W.Fe("remote","currentReceiver",this.F[a]);this.A.Ub()};
g.C(l9,g.Ju);g.h=l9.prototype;g.h.Rd=function(a){return this.Tc.$_gs(a)};
g.h.contains=function(a){return!!this.Tc.$_c(a)};
g.h.get=function(a){return this.Tc.$_g(a)};
g.h.start=function(){this.Tc.$_st()};
g.h.no=function(a,b,c){this.Tc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Tc.$_r(a,b,c)};
g.h.Yn=function(a,b,c,d){this.Tc.$_un(a,b,c,d)};
g.h.O=function(){for(var a=0,b=this.o.length;a<b;++a)this.Tc.$_ubk(this.o[a]);this.o.length=0;this.Tc=null;l9.P.O.call(this)};
g.h.sQ=function(){this.U("screenChange")};
g.h.PM=function(){this.U("onlineScreenChange")};
var q9=null,x9=[],z9=null,C9=null;g.C(J9,g.fs);g.h=J9.prototype;g.h.play=function(){1==this.g?(this.o?this.o.play(null,g.y,Q9(this,"play")):L9(this,"play"),O9(this,1,g.fe(K9(this))),this.U("remotePlayerChange")):N9(this,this.play)};
g.h.pause=function(){1==this.g?(this.o?this.o.pause(null,g.y,Q9(this,"pause")):L9(this,"pause"),O9(this,2,g.fe(K9(this))),this.U("remotePlayerChange")):N9(this,this.pause)};
g.h.ZA=function(a){if(1==this.g){if(this.o){var b=K9(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.sb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.o.seek(c,g.y,Q9(this,"seekTo",{newTime:a}))}else L9(this,"seekTo",{newTime:a});O9(this,3,a);this.U("remotePlayerChange")}else N9(this,g.ya(this.ZA,a))};
g.h.stop=function(){if(1==this.g){this.o?this.o.stop(null,g.y,Q9(this,"stopVideo")):L9(this,"stopVideo");var a=K9(this);a.index=-1;a.videoId="";g.de(a);M9(this,a);this.U("remotePlayerChange")}else N9(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=K9(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.B)(function(){P9("set receiver volume: "+d)},this),(0,g.B)(function(){this.dc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.B)(function(){P9("set receiver muted: "+b)},this),(0,g.B)(function(){this.dc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);L9(this,"setVolume",e)}c.muted=b;c.volume=a;M9(this,c)}else N9(this,g.ya(this.setVolume,a,b))};
g.h.sA=function(a,b){if(1==this.g){var c=K9(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.pb(b.style),g.Ob(d,c.o));L9(this,"setSubtitlesTrack",d);M9(this,c)}else N9(this,g.ya(this.sA,a,b))};
g.h.Os=function(a,b){if(1==this.g){L9(this,"setAudioTrack",{videoId:a,audioTrackId:b.Jc.id});var c=K9(this);c.audioTrackId=b.Jc.id;M9(this,c)}else N9(this,g.ya(this.Os,a,b))};
g.h.YA=function(a,b){if(1==this.g){if(a&&b){var c=K9(this);g.ge(c,a,b);M9(this,c)}L9(this,"previous")}else N9(this,g.ya(this.YA,a,b))};
g.h.XA=function(a,b){if(1==this.g){if(a&&b){var c=K9(this);g.ge(c,a,b);M9(this,c)}L9(this,"next")}else N9(this,g.ya(this.XA,a,b))};
g.h.Av=function(){1==this.g?L9(this,"dismissAutoplay"):N9(this,this.Av)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.U("proxyStateChange",a,this.g)}J9.P.dispose.call(this)};
g.h.O=function(){Sva(this);this.B=null;this.C.clear();I9(this,null);J9.P.O.call(this)};
g.h.Ps=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.U("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)g.ei(this.C).apply(this);else 3==a&&this.dispose()}};
g.h.jN=function(a,b){this.U(a,b)};
g.h.ZK=function(a){if(!a)this.Bk(null),I9(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=K9(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)P9("Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,M9(this,b)}};
g.h.Bk=function(a){P9("Cast media: "+!!a);this.o&&this.o.removeUpdateListener(this.G);if(this.o=a)this.o.addUpdateListener(this.G),Tva(this),this.U("remotePlayerChange")};
g.h.YK=function(a){a?(Tva(this),this.U("remotePlayerChange")):this.Bk(null)};
g.h.mL=function(){var a=Lva();a&&I9(this,a)};
g.h.dc=function(a){g.Qi("CP",a)};
var T9=[];g.h=ewa.prototype;g.h.Gh=function(a,b,c){var d=this.g;if(g.t(c)?c:this.o)d="https://"+this.A+this.port+this.g;return g.If(d+a,b||{})};
g.h.Ns=function(a,b,c,d){c={format:"JSON",method:"POST",context:this,timeout:5E3,withCredentials:!1,Ib:g.ya(this.nQ,c,!0),onError:g.ya(this.mQ,d),Uc:g.ya(this.oQ,d)};b&&(c.Nb=b,c.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Ox(a,c)};
g.h.nQ=function(a,b,c,d){b?a(d):a({text:c.responseText})};
g.h.mQ=function(a,b){a(Error("Request error: "+b.status))};
g.h.oQ=function(a){a(Error("request timed out"))};
g.C(V9,g.J);g.h=V9.prototype;
g.h.O=function(){V9.P.O.call(this);this.o.stop();this.A.stop();this.J();this.W.removeEventListener("onVolumeChange",this.sn,this);this.W.removeEventListener("onCaptionsTrackListChanged",this.Yy,this);this.W.removeEventListener("captionschanged",this.My,this);this.W.removeEventListener("videoplayerreset",this.Ek,this);this.W.removeEventListener("captionssettingschanged",this.gs,this);this.W.removeEventListener("mdxautoplaycancel",this.Lu,this);this.g.unsubscribe("proxyStateChange",this.mz,this);this.g.unsubscribe("remotePlayerChange",
this.Dk,this);this.g.unsubscribe("remoteQueueChange",this.Ek,this);this.g.unsubscribe("autoplayUpNext",this.Ky,this);this.g.unsubscribe("previousNextChange",this.jz,this);this.g.unsubscribe("nowAutoplaying",this.bz,this);this.g.unsubscribe("autoplayDismissed",this.Jy,this);this.g=this.H=null};
g.h.NB=function(a,b){2==this.g.g||(Y9(this)?this.KG.apply(this,arguments):this.GG.apply(this,arguments))};
g.h.My=function(a){this.NB("control_subtitles_set_track",g.Ib(a)?null:a)};
g.h.gs=function(){var a=this.W.Wc("captions","track");g.Ib(a)||$9(this,a)};
g.h.GG=function(a,b){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":a$(this,this.W.getCurrentTime());break;case "control_seek":a$(this,c[0]);break;case "control_subtitles_set_track":$9(this,c[0]);break;case "control_set_audio_track":c=c[0],Y9(this)&&this.g.Os(Z9(this),c)}};
g.h.KG=function(a,b){if(1081!=K9(this.g).g||"control_seek"!=a){var c=Array.prototype.slice.call(arguments,1);switch(a){case "control_toggle_play_pause":K9(this.g).sb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.F.Ii(c[0],c[1]);break;case "control_subtitles_set_track":$9(this,c[0]);break;case "control_set_audio_track":c=c[0],Y9(this)&&this.g.Os(Z9(this),c)}}};
g.h.sn=function(a){if(Y9(this)){this.g.unsubscribe("remotePlayerChange",this.Dk,this);var b=Math.round(a.volume);a=!!a.muted;var c=K9(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.G.start();this.g.subscribe("remotePlayerChange",this.Dk,this)}};
g.h.Yy=function(){g.Ib(this.B)||iwa(this,this.B);this.C=!1};
g.h.mz=function(a,b){this.A.stop();2==b&&this.zA()};
g.h.Dk=function(){if(Y9(this)){this.o.stop();var a=K9(this.g);switch(a.g){case 1081:X9(this,new g.XH(8));break;case 1:this.yA();X9(this,new g.XH(8));break;case 1083:case 3:X9(this,new g.XH(9));break;case 0:X9(this,new g.XH(2));this.F.stop();W9(this,this.W.getVideoData().lengthSeconds);break;case 1082:X9(this,new g.XH(4));break;case 2:X9(this,new g.XH(4));W9(this,g.fe(a));break;case -1:X9(this,new g.XH(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.M("YTP_MDX_PLAYER_ERROR")},X9(this,
new g.XH(128,a))}var a=K9(this.g).o,b=this.B;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.B=a,iwa(this,a));a=K9(this.g);-1==a.volume||Math.round(this.W.getVolume())==a.volume&&this.W.De()==a.muted||this.G.isActive()||this.OA()}else hwa(this)};
g.h.jz=function(){this.W.U("mdxpreviousnextchange")};
g.h.Ek=function(){Y9(this)||hwa(this)};
g.h.Lu=function(){this.g.Av()};
g.h.Ky=function(a){a&&(a=g.Ox("/watch_queue_ajax",{method:"GET",Nc:{action_get_watch_queue_item:1,video_id:a},Ib:(0,g.B)(this.kO,this)}))&&(this.J=(0,g.B)(a.abort,a))};
g.h.kO=function(a,b){var c=new g.xV({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.W.U("mdxautoplayupnext",c)};
g.h.bz=function(a){(0,window.isNaN)(a)||this.W.U("mdxnowautoplaying",a)};
g.h.Jy=function(){this.W.U("mdxautoplaycanceled")};
g.h.jS=function(a,b){-1==K9(this.g).g?a$(this,a):b&&this.g.ZA(a)};
g.h.OA=function(){if(Y9(this)){var a=K9(this.g);this.W.removeEventListener("onVolumeChange",this.sn,this);a.muted?this.W.mute():this.W.yg();this.W.setVolume(a.volume);this.W.addEventListener("onVolumeChange",this.sn,this)}};
g.h.yA=function(){this.o.stop();if(!this.g.la()){var a=K9(this.g);a.sb()&&X9(this,new g.XH(8));W9(this,g.fe(a));this.o.start()}};
g.h.zA=function(){this.A.stop();this.o.stop();var a=this.g.B.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.A.start()};g.p(b$,g.W);b$.prototype.B=function(a){kwa(this,a.state)};g.C(c$,g.Tu);g.h=c$.prototype;g.h.create=function(){gwa("embedded"==g.Y(this.g).g);this.D.push(g.ks("yt-remote-before-disconnect",this.VK,this));this.D.push(g.ks("yt-remote-connection-change",this.tN,this));this.D.push(g.ks("yt-remote-receiver-availability-change",this.kz,this));this.D.push(g.ks("yt-remote-auto-connect",this.rN,this));this.D.push(g.ks("yt-remote-receiver-resumed",this.qN,this));this.kz()};
g.h.load=function(){this.g.pp();c$.P.load.call(this);this.C=new V9(this,this.g,this.o);var a;a=(a=Jva())?a.currentTime:0;var b=G9()?new J9(n9(),void 0):null;0==a&&b&&(a=g.fe(K9(b)));0!=a&&(this.H=a||0,this.g.U("progresssync",a,void 0));jwa(this,this.F,this.F);g.v2(this.g.app,6)};
g.h.unload=function(){this.g.U("mdxautoplaycanceled");this.B=this.A;g.Hd(this.C,this.o);this.o=this.C=null;c$.P.unload.call(this);g.v2(this.g.app,5)};
g.h.O=function(){g.ls(this.D);c$.P.O.call(this)};
g.h.jl=function(a,b){this.loaded&&this.C.NB.apply(this.C,arguments)};
g.h.lG=function(){return this.loaded?this.C.suggestion:null};
g.h.Af=function(){return this.o?K9(this.o).Af:!1};
g.h.hasNext=function(){return this.o?K9(this.o).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.OR=function(){var a=K9(this.o),b=this.g.getVideoData(),c=this.g.Bd(),d=b.clipEnd,b=b.clipStart,e=this.getCurrentTime(),f=a.getDuration(),k;k=a.H?a.B+((0,g.D)()-a.A)/1E3:a.B;var l=1>=Ava(a)-this.getCurrentTime(),m=a.J,n=Ava(a),a=0<a.C?a.C+((0,g.D)()-a.A)/1E3:a.C;return{allowSeeking:c,clipEnd:d,clipStart:b,current:e,displayedStart:-1,duration:f,ingestionTime:k,isPeggedToLive:l,loaded:m,seekableEnd:n,seekableStart:a}};
g.h.PR=function(){this.o&&this.o.XA()};
g.h.QR=function(){this.o&&this.o.YA()};
g.h.VK=function(a){1==a&&(this.J=this.o?K9(this.o):null)};
g.h.tN=function(){var a=G9()?new J9(n9(),void 0):null;if(a){var b=this.B;this.loaded&&this.unload();this.o=a;this.J=null;b.key!=this.A.key&&(this.B=b,this.load())}else g.Gd(this.o),this.o=null,this.loaded&&(this.unload(),(a=this.J)&&a.videoId==this.g.getVideoData().videoId&&this.g.iB(a.videoId,g.fe(a)));this.g.U("videodatachange","newdata",this.g.getVideoData(),3)};
g.h.kz=function(){this.G=[this.A].concat(fwa());var a=S9()||this.A;d$(this,a);this.g.ya("onMdxReceiversChange")};
g.h.rN=function(){var a=S9();d$(this,a)};
g.h.qN=function(){this.B=S9()};
g.h.NR=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.G;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?U9():d$(this,b)),this.loaded?this.B:this.A;case "quickCast":return 2==this.G.length&&"cast-selector-receiver"==this.G[1].key?(b&&U9(),!0):!1}};
g.h.RR=function(){L9(this.o,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.ze=function(){return!1};window._exportCheck==g.Ba&&g.v("ytmod.player.remote",c$,void 0);})(_yt_player);
